// <auto-generated />
namespace EnterpriseWebProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class s2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(s2));
        
        string IMigrationMetadata.Id
        {
            get { return "202104030433337_s2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
